#!/bin/bash
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --gres=gpu:1
#SBATCH -p debug
#SBATCH --job-name=thermalReID

#SBATCH --mail-user t.a.robson@durham.ac.uk
#SBATCH --mail-type=[ALL]

#SBATCH -e stderr-filename
#SBATCH -o stdout-filename

module load cuda/8.0-cudnn6
module load opencv/3.4-py3

python3 networkExperimentation.py